# Generated by Django 4.2.1 on 2023-07-28 08:53

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Master',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, verbose_name='name')),
                ('portfolio', models.TextField(verbose_name='portfolio')),
                ('status', models.CharField(max_length=100, verbose_name='status')),
                ('avatar', models.CharField(max_length=50, verbose_name='avatar')),
                ('alias', models.CharField(max_length=50, verbose_name='alias')),
                ('phone_number', models.CharField(max_length=12, verbose_name='phone_number')),
                ('vk', models.CharField(max_length=100, verbose_name='vk')),
                ('tg', models.CharField(max_length=100, verbose_name='tg')),
            ],
        ),
        migrations.CreateModel(
            name='PortfolioFiles',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('filename', models.CharField(max_length=100, verbose_name='filename')),
                ('master', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='master.master')),
            ],
        ),
    ]
